# Generated by Django 6.0.5 on 2026-05-10 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_course_slug', models.CharField(blank=True, max_length=120)),
                ('last_lesson_slug', models.CharField(blank=True, max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_slug', models.CharField(max_length=120)),
                ('lesson_slug', models.CharField(max_length=160)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course_slug', 'lesson_slug'],
                'indexes': [models.Index(fields=['user', 'course_slug'], name='progress_le_user_id_1ccf2f_idx'), models.Index(fields=['user', 'lesson_slug'], name='progress_le_user_id_d96431_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'course_slug', 'lesson_slug'), name='unique_lesson_progress_per_user')],
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('solved', 'Solved')], default='not_started', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['task_id'],
                'indexes': [models.Index(fields=['user', 'task_id'], name='progress_ta_user_id_89fcd8_idx'), models.Index(fields=['user', 'status'], name='progress_ta_user_id_434401_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'task_id'), name='unique_task_progress_per_user')],
            },
        ),
    ]
