# Generated by Django 6.0.5 on 2026-06-27 16:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerTaskVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=160, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers and hyphens only.', regex='^[a-z0-9][a-z0-9-]*$')])),
                ('task_version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('course_slug', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers and hyphens only.', regex='^[a-z0-9][a-z0-9-]*$')])),
                ('lesson_slug', models.CharField(max_length=160, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers and hyphens only.', regex='^[a-z0-9][a-z0-9-]*$')])),
                ('language', models.CharField(choices=[('cpp17', 'C++17')], default='cpp17', max_length=16)),
                ('comparison_mode', models.CharField(choices=[('exact', 'Exact'), ('trimmed_lines', 'Trimmed lines'), ('tokens', 'Tokens')], default='exact', max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('source_limit_bytes', models.PositiveIntegerField(default=65536, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65536)])),
                ('compile_timeout_ms', models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(60000)])),
                ('run_timeout_ms', models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(30000)])),
                ('memory_limit_kb', models.PositiveIntegerField(default=131072, validators=[django.core.validators.MinValueValidator(16384), django.core.validators.MaxValueValidator(524288)])),
                ('output_limit_bytes', models.PositiveIntegerField(default=65536, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65536)])),
                ('enabled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['task_id', '-task_version'],
                'indexes': [models.Index(fields=['task_id', 'is_enabled'], name='checker_che_task_id_3e9a7d_idx'), models.Index(fields=['course_slug', 'lesson_slug'], name='checker_che_course__c2064c_idx')],
                'constraints': [models.UniqueConstraint(fields=('task_id', 'task_version'), name='unique_checker_task_version'), models.UniqueConstraint(condition=models.Q(('is_enabled', True)), fields=('task_id',), name='unique_enabled_checker_task')],
            },
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(editable=False, max_length=160)),
                ('task_version', models.PositiveIntegerField(editable=False)),
                ('course_slug', models.CharField(editable=False, max_length=120)),
                ('lesson_slug', models.CharField(editable=False, max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('passed', 'Passed'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('code_snapshot', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(65536)])),
                ('note', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checker_task_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='checker.checkertaskversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checker_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('cpp17', 'C++17')], default='cpp17', max_length=16)),
                ('source_code', models.TextField(validators=[django.core.validators.MaxLengthValidator(65536)])),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('compiling', 'Compiling'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('compiler_error', 'Compiler error'), ('runtime_error', 'Runtime error'), ('timeout', 'Timeout'), ('output_limit', 'Output limit'), ('system_error', 'System error'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('compiler_output', models.TextField(blank=True)),
                ('runtime_output', models.TextField(blank=True)),
                ('passed_tests', models.PositiveIntegerField(default=0)),
                ('failed_tests', models.PositiveIntegerField(default=0)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_used_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='checker.taskattempt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(65536)])),
                ('expected_output', models.TextField(validators=[django.core.validators.MaxLengthValidator(65536)])),
                ('is_hidden', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('explanation', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('position', models.PositiveIntegerField(default=0)),
                ('task_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='checker.checkertaskversion')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['user', 'task_id', 'task_version'], name='checker_tas_user_id_943608_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['user', 'status'], name='checker_tas_user_id_f6a487_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'archived'), _negated=True), fields=('user', 'task_id', 'task_version'), name='unique_active_attempt_per_task_version'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['attempt', '-created_at'], name='checker_sub_attempt_d8beeb_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'created_at'], name='checker_sub_status_3642d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('task_version', 'position'), name='unique_test_position_per_task_version'),
        ),
    ]
