# Generated by Django 6.0.5 on 2026-06-30 16:14

from django.db import migrations, models


def normalize_status_names(apps, _schema_editor):
    TaskAttempt = apps.get_model("checker", "TaskAttempt")
    Submission = apps.get_model("checker", "Submission")

    TaskAttempt.objects.filter(status="passed").update(status="accepted")

    for old_status, new_status in {
        "passed": "accepted",
        "failed": "wrong_answer",
        "compiler_error": "compile_error",
        "timeout": "time_limit",
        "system_error": "internal_error",
        "cancelled": "internal_error",
    }.items():
        Submission.objects.filter(status=old_status).update(status=new_status)


def restore_legacy_status_names(apps, _schema_editor):
    TaskAttempt = apps.get_model("checker", "TaskAttempt")
    Submission = apps.get_model("checker", "Submission")

    TaskAttempt.objects.filter(status="accepted").update(status="passed")

    # Best-effort reverse mapping: legacy "cancelled" cannot be reconstructed
    # after it has been folded into canonical "internal_error".
    for canonical_status, old_status in {
        "accepted": "passed",
        "wrong_answer": "failed",
        "compile_error": "compiler_error",
        "time_limit": "timeout",
        "internal_error": "system_error",
    }.items():
        Submission.objects.filter(status=canonical_status).update(status=old_status)


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_status_names, restore_legacy_status_names),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('compiling', 'Compiling'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong answer'), ('compile_error', 'Compile error'), ('runtime_error', 'Runtime error'), ('time_limit', 'Time limit'), ('output_limit', 'Output limit'), ('internal_error', 'Internal error')], default='queued', max_length=32),
        ),
        migrations.AlterField(
            model_name='taskattempt',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('accepted', 'Accepted'), ('archived', 'Archived')], default='draft', max_length=32),
        ),
    ]
