# Generated by Django 6.0.5 on 2026-05-12 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('requests_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_daily_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'user_id'],
                'indexes': [models.Index(fields=['user', 'date'], name='ai_aidailyu_user_id_46ebc0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_ai_daily_usage_per_user')],
            },
        ),
    ]
