# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_phoneverificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_token_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
